#!/bin/bash

# Color definitions
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
nc='\033[0m'  # No color

# ASCII banner
echo -e "
${red}██████╗ ██████╗ ██╗      █████╗  ██████╗██╗  ██╗
██╔══██╗██╔═══██╗██║     ██╔══██╗██╔════╝██║ ██╔╝
██████╔╝██║   ██║██║     ███████║██║     █████╔╝ 
██╔═══╝ ██║   ██║██║     ██╔══██║██║     ██╔═██╗ 
██║     ╚██████╔╝███████╗██║  ██║╚██████╗██║  ██╗
╚═╝      ╚═════╝ ╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝${nc}
${magenta}Black-eye-scanner${nc}
"

# Definition of URLs and attacks
urls=("http://lad-app-pro-w01:8080/vrisk/app/" 
"http://bi1-shp-pro-w01:36280/pages/inicio.aspx"
"http://lad-app-pro-w01:8080/vrisk/app/"
"http://bi1-shp-pro-w01:36280/pages/inicio.aspx"
"http://fid-app-pro-w01/protrust/"
"https://myshf.shf.gob.mx/scad"
"http://ikc-app-pro-w01:4106/app/index.html#!/loginoauth"
"http://wre-app-pro-w02/reportware5_shf/login/login"
"http://wre-app-pro-w01/bajawaremxfovi/login.aspx"
"http://wre-app-pro-w01/bajawaremx/login.aspx"
"http://shffnprod1:9080/workplace/browse.jsp"
"https://kmi-app-pro-w01/miportal/default.aspx"
"https://abc-app-pro-w01/myabcmcorporate/loginpage.aspx"
"https://myshf.shf.gob.mx/"
"https://myshf.shf.gob.mx/"
"https://myshf.shf.gob.mx/sci"
"https://myshf.shf.gob.mx/"
"https://sma.shf.gob.mx:449/account/login?returnurl=%2f"
"https://myshf.shf.gob.mx/cobranza/"
"https://myshf.shf.gob.mx/scv/login.aspx"
"https://rh.shf.gob.mx/"
"https://pfi-app-pro-w02:8443/dashboard/index.htm"
"https://myshf.shf.gob.mx/sig/login.aspx"
)
attacks=(
  "SQL Injection (sqlmap)"
  "XSS (xsser)"
  "CSRF (OWASP ZAP)"
  "Path Traversal (ZAPROXY)"
  "Insecure Error Handling (ZAPROXY)"
  "HTML Comments (ZAPROXY)"
  "Metadata Exposure (metagoofil)"
  "OS Command Injection (ZAPROXY)"
  "LDAP Injection (ldapsearch)"
  "Parameter Tampering (ZAPROXY)"
  "Cookie Poisoning (ZAPROXY)"
  "Hidden Field Manipulation (ZAPROXY)"
  "Input Field Validation (ZAPROXY)"
)


# Function to simulate an attack with a progress bar
simulate_attack() {
  target="$1"
  attack="$2"
  real_duration=$((RANDOM % 10 + 1))

  echo -n "${blue}Target ${target} with ${attack}...${nc}"

  # Simulate the progress bar
  progress_bar="▓"
  bar_width=50

  for ((i=1; i<=bar_width; i++)); do
    sleep $((real_duration / bar_width))
    printf "%s" "$progress_bar"
  done

  echo  # New line
  echo -e "${green}Deploying security checks completed in ${real_duration} seconds.${nc}"
}

# Main loop to iterate over URLs and attacks
for url in "${urls[@]}"; do
  echo -e "${blue}Target: ${url}${nc}"

  for attack in "${attacks[@]}"; do
    simulate_attack "$url" "$attack"
  done

  echo -e "${green}Finished with ${url}.${nc}"
done

echo -e "${blue}All targets scanned.${nc}"


